pull-request:
      needs: regression-tests
      name: Github Pull Request
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "👑 *An automated PR test*"
          pr_reviewer: "Kev"
          github_token: ${{ secrets.GITHUB_TOKEN }}
